Repository FRONTENDBOOTCAMP-13th/JS-05-teeniepingworld, pull requests merged in 2025-05, with the labels that each got.

#16 feature/15-addCommonCss-kjh
  src/common/a11y.css
  src/common/font.css
  src/common/modern-reset.css
  src/common/theme.css
Labels: ⚙️ Setting

#20 feature/18-파일추가-osh
  src/assets/teenieping_img/hachuPing.png
Labels: 📝 Docs, ⚙️ Setting

#21 feature/13-memory game-kjh
  src/pages/memoryGame.html
  src/pages/memoryGameStart.html
  src/styles/memoryGame.css
  src/styles/memoryGameStart.css
  src/typescript/memoryGame/memoryGameStart.ts
  src/typescript/memoryGame/memoryGameTitle.ts
Labels: ✨Feature, 💄 Html&Css

#23 feature/14-findteeniepingGame-ysw
  src/assets/findGame/ayaPingFail.WEBP
  src/assets/findGame/ayaPingSuccess.PNG
  src/assets/findGame/bbanzzakPing.WEBP
  src/assets/findGame/bbanzzakPingCube.PNG
  src/assets/findGame/ruruPing.PNG
  src/assets/findGame/ruruPingCube.PNG
  src/assets/findGame/ruruPingCubeOpen.PNG
  src/pages/findGame.html
  src/styles/findGame.css
  src/types/type-findGame.ts
  src/typescript/findGame/findGame.ts
Labels: 💄 Html&Css

#34 🚑 Critical hotfix.: 1
  index.html
  vite.config.js
Labels: 🌎 Deploy

#35 1차 배포 테스트
  index.html
  vite.config.js
Labels: 🌎 Deploy

#38 feature/37-teenieping worldcup game-ktw
  src/pages/worldcupGame.html
  src/styles/worldcupGame.css
  src/typescript/worldcupGame/worldcupGameMain.ts
Labels: ♻️ Refactor, 💄 Html&Css

#39 feature/36-typetestui-osh
  index.html
  src/assets/teenieping_img/iingPing.webp
  src/assets/teenieping_img/repeatPing.webp
  src/assets/teenieping_img/smartPing.webp
  src/assets/typeTest_img/Frame.png
  src/assets/typeTest_img/repeat.png
  src/assets/typeTest_img/share.png
  src/pages/typeTestResult.html
  src/pages/typeTestStart.html
  src/styles/typeTestResult.css
  src/styles/typeTestStart.css
Labels: 💄 Html&Css

#44 feature/22-memorygame ts-kjh
  src/assets/memorygame_img/aingPing.webp
  src/assets/memorygame_img/ajaPing.webp
  src/assets/memorygame_img/backCard.png
  src/assets/memorygame_img/baebaePing.webp
  src/assets/memorygame_img/baroPing.webp
  src/assets/memorygame_img/bugguPing.webp
  src/assets/memorygame_img/chachaPing.webp
  src/assets/memorygame_img/dockdockPing.webp
  src/assets/memorygame_img/haePing.webp
  src/assets/memorygame_img/haunaPing.webp
  src/assets/memorygame_img/heartsping.webp
  src/assets/memorygame_img/kikiPing.webp
  src/assets/memorygame_img/kojaPing.webp
  src/assets/memorygame_img/moyaPing.webp
  src/assets/memorygame_img/mugouPing.webp
  src/assets/memorygame_img/raraPing.webp
  src/assets/memorygame_img/siruping.webp
  src/pages/memoryGame.html
  src/pages/memoryGameStart.html
  src/styles/memoryGame.css
  src/styles/memoryGameStart.css
  src/typescript/memoryGame/memoryGameStart.ts
  src/typescript/memoryGame/memoryGameTitle.ts
Labels: ✨Feature, 💄 Html&Css

#45 feature/24-findteeniepingGameTS-ysw
  .vscode/settings.json
  src/assets/findGame/ayaPingSuccess.WEBP
  src/assets/findGame/bbanzzakPingCube.WEBP
  src/assets/findGame/bbanzzakPingCubeOpen.WEBP
  src/assets/findGame/ruruPing.WEBP
  src/assets/findGame/ruruPingCube.WEBP
  src/assets/findGame/ruruPingCubeOpen.WEBP
  src/pages/findGame.html
  src/styles/findGame.css
  src/types/findGameType.ts
  src/types/type-findGame.ts
  src/typescript/findGame/findGame.ts
  src/typescript/findGame/findGameRound.ts
  src/typescript/findGame/findGameUtils.ts
Labels: ✨Feature

#46 feature/42-typetestfunction-osh
  index.html
  src/pages/typeTest.html
  src/pages/typeTestResult.html
  src/pages/typeTestStart.html
  src/typescript/typeTest/fixDate.ts
  src/typescript/typeTest/gameTypeTest.ts
  src/typescript/typeTest/mainTypeTest.ts
  src/typescript/typeTest/resultTypeTest.ts
Labels: ✨Feature

#49 🔧 Add or update configuration files: Add teeniepingDatabase
  src/typescript/dataBase.ts
  src/typescript/worldcupGame/worldcupGame-start.ts
Labels: ✨Feature

#51 feature/24-findteeniepingGameTS-ysw
  src/pages/findGame.html
  src/styles/findGame.css
  src/types/findGameType.ts
  src/typescript/findGame/findGame.ts
  src/typescript/findGame/findGameRound.ts
  src/typescript/findGame/findGameUtils.ts
Labels: ✨Feature, ♻️ Refactor, 💄 Html&Css

#52 Feature/47-typetest-osh
  index.html
  src/assets/teenieping_img/arapping.webp
  src/assets/teenieping_img/azaping.webp
  src/assets/teenieping_img/beepping.webp
  src/assets/teenieping_img/cojaping.webp
  src/assets/teenieping_img/drawping.webp
  src/assets/teenieping_img/eleping.webp
  src/assets/teenieping_img/fossilPing.webp
  src/assets/teenieping_img/holaping.webp
  src/assets/teenieping_img/nanumPing.webp
  src/assets/teenieping_img/partying.webp
  src/assets/teenieping_img/pattping.webp
  src/assets/teenieping_img/shashaping.webp
  src/assets/teenieping_img/snapping.webp
  src/assets/teenieping_img/yogaping.webp
  src/pages/typeTestResult.html
  src/pages/typeTestStart.html
  src/styles/typeTestResult.css
  src/styles/typeTestStart.css
  src/typescript/typeTest/fixData.ts
  src/typescript/typeTest/gameTypeTest.ts
  src/typescript/typeTest/pingData.ts
  src/typescript/typeTest/pingExpData.ts
  src/typescript/typeTest/resultTypeTest.ts
  src/typescript/typeTest/typeTestStart.ts
Labels: ✨Feature

#55 feature/28-worldcup game ts-ktw
  src/pages/worldcupGame.html
  src/styles/worldcupGame/worldcupGame.css
  src/typescript/dataBase.ts
  src/typescript/worldcupGame/worldcupGame-rank.ts
  src/typescript/worldcupGame/worldcupGame-search.ts
  src/typescript/worldcupGame/worldcupGame-start.ts
  src/typescript/worldcupGame/worldcupGameModal.ts
Labels: 🐛 BugFix, ✨Feature

#57 💩 Write bad code that needs to be improved: Fix error code
  src/typescript/worldcupGame/worldcupGame-start.ts
Labels: 🐛 BugFix

#58 feature/53-Improve structure-kjh
  src/assets/memorygame_bgm/startText.wav
  src/assets/memorygame_bgm/startText2.wav
  src/assets/memorygame_bgm/startText3.wav
  src/assets/memorygame_bgm/startText4.wav
  src/common/font.css
  src/common/fonts/BMHANNA_11yrs_ttf.ttf
  src/common/fonts/Maplestory_Bold.ttf
  src/common/fonts/Maplestory_Light.ttf
  src/pages/memoryGame.html
  src/pages/memoryGameStart.html
  src/styles/memoryGame.css
  src/styles/memoryGameStart.css
  src/typescript/memoryGame/memoryGameStart.ts
Labels: ✨Feature, ♻️ Refactor, 💄 Html&Css

#60 Feature/59-findteeniepingGameTS-ysw
  README.md
  src/assets/findgame_img/ayaPingFail.WEBP
  src/assets/findgame_img/ayaPingSuccess.WEBP
  src/assets/findgame_img/bbanzzakPing.WEBP
  src/assets/findgame_img/bbanzzakPingCube.WEBP
  src/assets/findgame_img/bbanzzakPingCubeOpen.WEBP
  src/assets/findgame_img/ruruPing.WEBP
  src/assets/findgame_img/ruruPingCube.WEBP
  src/assets/findgame_img/ruruPingCubeOpen.WEBP
  src/pages/findGame.html
  src/styles/findGame.css
  src/typescript/findGame/findGame.ts
  src/typescript/findGame/findGameDevTools.ts
  src/typescript/findGame/findGameMainUI.ts
  src/typescript/findGame/findGameRound.ts
  src/typescript/findGame/findGameUtils.ts
Labels: 📝 Docs, ✨Feature, ♻️ Refactor

#61 ✨ Introduce new features: API
  src/assets/teenieping_img/kurapping.webp
  src/assets/typeTest_img/close.png
  src/assets/typeTest_img/copy.svg
  src/assets/typeTest_img/facebook.png
  src/assets/typeTest_img/instagram.png
  src/assets/typeTest_img/kakao.png
  src/pages/typeTestResult.html
  src/pages/typeTestStart.html
  src/styles/typeTestResult.css
  src/styles/typeTestStart.css
  src/typescript/dataBase.ts
  src/typescript/typeTest/resultModal.ts
  src/typescript/typeTest/resultTypeTest.ts
  src/typescript/typeTest/typeTestStart.ts
Labels: ✨Feature

#65 Feature/63 test team
  src/typescript/dataBase.ts
Labels: 🐛 BugFix

#72 🚚 Move or rename resources : move
  public/teenieping_img/arapping.webp
  public/teenieping_img/azaping.webp
  public/teenieping_img/beepping.webp
  public/teenieping_img/cojaping.webp
  public/teenieping_img/drawping.webp
  public/teenieping_img/eleping.webp
  public/teenieping_img/fosilping.webp
  public/teenieping_img/hachuuping.png
  public/teenieping_img/holaping.webp
  public/teenieping_img/iinggping.webp
  public/teenieping_img/kurapping.webp
  public/teenieping_img/melloping.webp
  public/teenieping_img/nanummping.webp
  public/teenieping_img/partyping.webp
  public/teenieping_img/pattping.webp
  public/teenieping_img/repeatpping.webp
  public/teenieping_img/shashaping.webp
  public/teenieping_img/singsingpping.webp
  public/teenieping_img/smartpping.webp
  public/teenieping_img/snapping.webp
  public/teenieping_img/thawbumpping.webp
  public/teenieping_img/yogaping.webp
  src/pages/typeTest.html
  src/pages/typeTestResult.html
  src/typescript/typeTest/pingData.ts
  src/typescript/typeTest/resultTypeTest.ts
  vite.config.js
Labels: 🐛 BugFix, 📝 Docs, ♻️ Refactor

#81 feature/76-add main page-kjh
  src/main.ts
  src/pages/main.html
  src/styles/main.css
Labels: ✨Feature, 💄 Html&Css

#83 feature/79-indexui-ysw
  README.md
  index.html
  src/style.css
Labels: ✨Feature, 💄 Html&Css

#85 feature/78-worldcupgameuiux improvements-ktw
  public/teenieping-local-img/134-seulbiping.webp
  public/teenieping-local-img/135-gdping.webp
  public/worldcupGame_img/home-tnp.png
  src/assets/teenieping-local-img/134-seulbiping.webp
  src/assets/teenieping-local-img/135-gdping.webp
  src/assets/worldcupGame_img/home-tnp.png
  src/common/font.css
  src/pages/worldcupGame.html
  src/style.css
  src/styles/worldcupGame/worldcupGame.css
  src/styles/worldcupGame/worldcupGameModal.css
  src/typescript/dataBase.ts
  src/typescript/worldcupGame/worldcupGame-likelion.ts
  src/typescript/worldcupGame/worldcupGame-rank.ts
  src/typescript/worldcupGame/worldcupGame-start.ts
  src/typescript/worldcupGame/worldcupGameModal.ts
Labels: ♻️ Refactor, 💄 Html&Css

#89 feat/75-findgame UI improvements-ysw
  index.html
  public/findgame_img/home.png
  src/assets/findgame_img/bbanzzakPingCubeOpen.WEBP
  src/assets/findgame_img/bitnaPing.WEBP
  src/assets/findgame_img/bitnaPingCube.WEBP
  src/assets/findgame_img/bitnaPingCubeOpen.WEBP
  src/pages/findGame.html
  src/style.css
  src/styles/findGame.css
  src/typescript/findGame/findGame.ts
  src/typescript/findGame/findGameDevTools.ts
  src/typescript/findGame/findGameMainUI.ts
  src/typescript/findGame/findGameRound.ts
  src/typescript/findGame/findGameUtils.ts
Labels: 🐛 BugFix, ♻️ Refactor, 💄 Html&Css

#91 Feature/87 additional features osh
  index.html
  public/_redirects
  public/typeTest_bgm/typetest.mp3
  public/typeTest_img/mp3off.png
  public/typeTest_img/mp3on.png
  src/pages/typeTest.html
  src/pages/typeTestResult.html
  src/pages/typeTestStart.html
  src/styles/typeTest.css
  src/styles/typeTestResult.css
  src/styles/typeTestStart.css
  src/typescript/typeTest/mainTypeTest.ts
  src/typescript/typeTest/resultTypeTest.ts
  src/typescript/typeTest/typeTestStart.ts
Labels: ✨Feature, 💄 Html&Css

#93 ♻️ Refactor code : Q&A
  index.html
  public/teeniepingworld.png
  public/vite.svg
  src/pages/findGame.html
  src/pages/main.html
  src/pages/memoryGame.html
  src/pages/memoryGameStart.html
  src/pages/typeTest.html
  src/pages/typeTestResult.html
  src/pages/typeTestStart.html
  src/pages/worldcupGame.html
  src/typescript/typeTest/fixData.ts
Labels: ♻️ Refactor, 💄 Html&Css

#94 feat/90-findgame UI improvements-ysw
  index.html
  src/assets/findgame_img/auroraPing.WEBP
  src/assets/findgame_img/auroraPingCube.WEBP
  src/assets/findgame_img/auroraPingCubeOpen.WEBP
  src/assets/findgame_img/bbanzzakPingCubeOpen.WEBP
  src/assets/findgame_img/bitnaPingCubeOpen.WEBP
  src/assets/findgame_img/swayPing.WEBP
  src/assets/findgame_img/swayPingCube.WEBP
  src/assets/findgame_img/swayPingCubeOpen.WEBP
  src/pages/findGame.html
  src/styles/findGame.css
  src/typescript/findGame/findGameMainUI.ts
  src/typescript/findGame/findGameRound.ts
  src/typescript/findGame/findGameUtils.ts
Labels: ♻️ Refactor, 💄 Html&Css

#98 feature/95-Sound control, button size control-kjh
  src/main.ts
  src/pages/main.html
  src/pages/memoryGame.html
  src/pages/memoryGameStart.html
  src/styles/main.css
  src/styles/memoryGame.css
  src/styles/memoryGameStart.css
  src/typescript/memoryGame/memoryGameStart.ts
Labels: ♻️ Refactor

#100 feature/90-findgame(ui)-ysw
  index.html
  public/findgame_bgm/findgame_1.wav
  public/findgame_bgm/findgame_2.wav
  public/findgame_bgm/findgame_3.wav
  public/findgame_bgm/findgame_4.wav
  public/findgame_bgm/findgame_5_1.wav
  public/findgame_bgm/findgame_5_2.wav
  public/findgame_bgm/findgame_6_1.wav
  public/findgame_bgm/findgame_6_2.wav
  src/pages/findGame.html
  src/style.css
  src/styles/findGame.css
  src/typescript/findGame/findGame.ts
  src/typescript/findGame/findGameMainUI.ts
  src/typescript/findGame/findGameRound.ts
  src/typescript/findGame/findGameUtils.ts
Labels: ✨Feature

#99 Refactor/96 audioui osh
  public/typeTest_bgm/voice.wav
  src/pages/typeTest.html
  src/pages/typeTestStart.html
  src/styles/typeTest.css
  src/styles/typeTestResult.css
  src/styles/typeTestStart.css
  src/typescript/typeTest/resultModal.ts
  src/typescript/typeTest/typeTestStart.ts
Labels: ✨Feature, ♻️ Refactor, 💄 Html&Css

#101 feat/findgame(ui)-ysw
  src/styles/findGame.css
Labels: 💄 Html&Css

#104 refactor/102-change audio volume-kjh
  src/typescript/memoryGame/memoryGameStart.ts
Labels: ♻️ Refactor

#107 feat/indexpage-ysw
  index.html
  public/index_img/jaehyunPing.png
  public/index_img/seohyunPing.png
  public/index_img/siwonPing.png
  public/index_img/taewooPing.png
  src/pages/findGame.html
  src/pages/main.html
  src/pages/typeTest.html
  src/pages/typeTestResult.html
  src/pages/typeTestStart.html
  src/pages/worldcupGame.html
  src/style.css
Labels: ✨Feature
